title: ibebrett
email: ibebrett@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ibebrett

exclude:
  - Gemfile
  - Gemfile.lock
theme: jekyll-theme-cayman
